[providers]
providers = ['node']

[phases.setup]
nixPkgs = ['pnpm']

[phases.install]
cmds = ['pnpm install --no-frozen-lockfile']

[phases.build]
cmds = ['pnpm --filter ./artifacts/api-server run build']

[start]
cmd = 'pnpm --filter ./artifacts/api-server run start'

[deploy]
startCmd = 'pnpm --filter ./artifacts/api-server run start'
